/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add` | `/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/status` | `/status`; params?: Router.UnknownInputParams; } | { pathname: `/add/step1-location`; params?: Router.UnknownInputParams; } | { pathname: `/add/step2-info`; params?: Router.UnknownInputParams; } | { pathname: `/add/step3-photos`; params?: Router.UnknownInputParams; } | { pathname: `/add/step4-details`; params?: Router.UnknownInputParams; } | { pathname: `/add/step5-review`; params?: Router.UnknownInputParams; } | { pathname: `/place/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/add` | `/add`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/status` | `/status`; params?: Router.UnknownOutputParams; } | { pathname: `/add/step1-location`; params?: Router.UnknownOutputParams; } | { pathname: `/add/step2-info`; params?: Router.UnknownOutputParams; } | { pathname: `/add/step3-photos`; params?: Router.UnknownOutputParams; } | { pathname: `/add/step4-details`; params?: Router.UnknownOutputParams; } | { pathname: `/add/step5-review`; params?: Router.UnknownOutputParams; } | { pathname: `/place/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/add${`?${string}` | `#${string}` | ''}` | `/add${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/status${`?${string}` | `#${string}` | ''}` | `/status${`?${string}` | `#${string}` | ''}` | `/add/step1-location${`?${string}` | `#${string}` | ''}` | `/add/step2-info${`?${string}` | `#${string}` | ''}` | `/add/step3-photos${`?${string}` | `#${string}` | ''}` | `/add/step4-details${`?${string}` | `#${string}` | ''}` | `/add/step5-review${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add` | `/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/status` | `/status`; params?: Router.UnknownInputParams; } | { pathname: `/add/step1-location`; params?: Router.UnknownInputParams; } | { pathname: `/add/step2-info`; params?: Router.UnknownInputParams; } | { pathname: `/add/step3-photos`; params?: Router.UnknownInputParams; } | { pathname: `/add/step4-details`; params?: Router.UnknownInputParams; } | { pathname: `/add/step5-review`; params?: Router.UnknownInputParams; } | `/place/${Router.SingleRoutePart<T>}` | { pathname: `/place/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
